services:
  php:
    container_name: tiny-kit
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
